<?php
if( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Collection of random and general functions
 */
include_once( 'inc/initialization.php' );

/**
 * Include all of your assets ( CSS & JS )
 */
include_once( 'inc/enqueue.php' );

/**
 * Function that enable the including of an CSS & JS in any file
 *
 * Note: Do not edit this file
 */
include_once( 'inc/include-assets.php' );

/**
 * Add custom image size
 */
include_once( 'inc/image-size.php' );

/**
 * A function that enable the passing of variables in inlcuding a partial file
 *
 * Note: Do not edit this file
 */
include_once( 'inc/views.php' );

/**
 * Main setting of your backend
 *
 * Note: Not required to edit this
 */
include_once( 'inc/theme-support.php' );

/**
 * Adding of menu
 */
include_once( 'inc/menus.php' );

/**
 * Adding of widgets
 */
include_once( 'inc/widgets.php' );

/**
 * Add a class in your body tag
 *
 * Note: Not required to edit this
 */
include_once( 'inc/body-class.php' );

/**
 * Setting of your website title
 *
 * Note: Not required to edit this
 */
include_once( 'inc/wp-title.php' );

/**
 * Guide in rewriting your url rules
 */
// include_once( 'inc/rewrite-rules.php' );

/**
 * To use this you need to install ACF Pro or ACF Options Plugin
 */
// include_once( 'inc/options.php' ); 

/**
 * To use this you need to install Advanced TinyMCE Plugin
 */
// include_once( 'inc/tinymce.php' );

/**
 * Customize your backend, especially your backend login page
 */
// include_once( 'inc/backend.php' );

/**
 * Enable the category in page post type
 */
// include_once( 'inc/page-cat.php' ); 

/**
 * Customize the term interface
 */
// include_once( 'inc/term-settings.php' );

/**
 * Include all the file inside the specify subfolder of functions folder
 */
include_all_php('posttype');
include_all_php('pregetpost');
include_all_php('shortcode');
include_all_php('taxonomy');

/**
 * Guide on how to name and include your AJAX Script ( PHP )
 */
// include_once( 'inc/ajax/function-name/function-name.php' );

/**
 * Guide on how to name and include your custom script ( PHP )
 *
 * For team project : custom-*.php
 * For individual project : custom.php
 */
// include_once( 'inc/file-name.php' );